services:
  backend:
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      - DB_CONN_STR=postgresql://postgres:postgres@postgres:5432/puzzle?sslmode=disable
    ports:
      - "8181:8181"
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=puzzle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
