name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [apps/backend, apps/frontend]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.folder }}
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/${{matrix.folder}}
          SHA=${{ github.sha }}
          # Build the Docker Image
          docker build -t $IMAGE_NAME:$SHA -t $IMAGE_NAME:latest ./${{matrix.folder}}
          # Push the image
          docker push $IMAGE_NAME:$SHA
          docker push $IMAGE_NAME:latest
      
      - name: Logout of ghcr
        run: docker logout ghcr.io
